import {ExportEvidence} from './ExportEvidence.jsx';
import {nestedRef} from '../../shared/research-continuity.mjs';
import {useEffect,useRef,useState} from 'react';
import {MagnifyingGlass,ArrowCounterClockwise,ArrowClockwise,DownloadSimple,Plus,Shapes,TextT,ArrowRight,Trash,FloppyDisk} from '@phosphor-icons/react';
import {emptyScene,validateScene,connector,edgeKinds,nodeLabelLines,sceneSvg,figureCredits,arrangeScene,sceneTemplate} from '../../shared/figure-workspace.mjs';
import {DataFigures} from './RevisionTools.jsx';
import {download} from './ui.jsx';
import './figure-workspace.css';
const uid=()=>`n-${crypto.randomUUID()}`,url=a=>`/api/scientific-assets/${a.id}`,copy=v=>structuredClone(v);
const bounded=(v,min,max)=>Math.min(max,Math.max(min,v));
export function FigureWorkspace(props){
 const {project,artifact,onRun,onTemplateEdit,disabled,task}=props,key=`rw2:figure-studio:${project.id}:${artifact.id}`;
 const figures=(artifact.topicWorkspace?.figures??[]).filter(f=>f.type==='illustration');
 const [initial]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??{scene:figures.at(-1)?.scene??emptyScene(),baseFigureId:figures.at(-1)?.id??null};}catch{return {scene:emptyScene(),baseFigureId:null};}});
 const [scene,setScene]=useState(initial.scene),[baseFigureId,setBase]=useState(initial.baseFigureId??null),[proposalId,setProposal]=useState(initial.proposalId??null),[catalog,setCatalog]=useState(null),[mode,setMode]=useState('illustration'),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[style,setStyle]=useState('all'),[selected,setSelected]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[history,setHistory]=useState([]),[future,setFuture]=useState([]),[relation,setRelation]=useState({from:'',to:'',kind:'activation'}),[widthMm,setWidthMm]=useState(180),[exporting,setExporting]=useState(false),[layout,setLayout]=useState('horizontal');
 const [linkCurrentResearch,setLinkCurrentResearch]=useState(false);
 const svgRef=useRef(),drag=useRef(),saving=useRef(null),current=useRef(scene);current.current=scene;
 useEffect(()=>{let live=true;fetch('/api/scientific-assets').then(async r=>{if(!r.ok)throw Error('素材库未加载，请重新打开此页。');return (await r.json()).data;}).then(v=>{if(live){try{validateScene(initial.scene,v);setCatalog(v);}catch(e){setError('已保留浏览器草稿，但它与当前素材库不兼容。请导出图稿结构备份后新建图稿。');setCatalog(v);}}}).catch(e=>live&&setError(e.message));return()=>{live=false;};},[]);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify({scene,baseFigureId,proposalId}));}catch{setError('浏览器暂存失败，请保存图稿版本或导出图稿结构。');}},[scene,baseFigureId,proposalId,key]);
 useEffect(()=>{if(!saving.current)return;const f=figures.findLast(f=>JSON.stringify(f.scene)===saving.current);if(f){setBase(f.id);saving.current=null;setNotice('图稿版本已保存，历史版本仍可打开。');}},[figures]);
 const change=next=>{const previous=copy(current.current);setHistory(h=>[...h.slice(-39),{scene:previous,baseFigureId,proposalId}]);setFuture([]);setScene(typeof next==='function'?next(current.current):next);setNotice('');};
 const undo=()=>{if(!history.length)return;setFuture(f=>[{scene:copy(scene),baseFigureId,proposalId},...f].slice(0,40));const previous=history.at(-1);setScene(previous.scene);if(previous.scene.id!==scene.id){setBase(previous.baseFigureId);setProposal(previous.proposalId);}setHistory(history.slice(0,-1));setSelected(null);};
 const redo=()=>{if(!future.length)return;setHistory(h=>[...h,{scene:copy(scene),baseFigureId,proposalId}]);const next=future[0];setScene(next.scene);if(next.scene.id!==scene.id){setBase(next.baseFigureId);setProposal(next.proposalId);}setFuture(future.slice(1));setSelected(null);};
 const node=scene.nodes.find(n=>n.id===selected),edge=scene.edges.find(e=>e.id===selected),asset=node?.type==='asset'?catalog?.assets.find(a=>a.id===node.assetId):null;
 const add=(type,a)=>{if(scene.nodes.length>=80){setError('单幅图最多 80 个元素。');return;}const id=uid(),n={id,type,label:a?.name??(type==='box'?'细胞内':'文字'),x:80+scene.nodes.length%4*35,y:100+scene.nodes.length%4*35,w:type==='box'?400:200,h:type==='box'?300:type==='text'?75:170,fontSize:22,color:'#304d4c',fill:'#edf4f0',...(a?{assetId:a.id}:{}),flip:false};change(s=>({...s,nodes:type==='box'?[n,...s.nodes]:[...s.nodes,n]}));setSelected(id);};
 const updateNode=patch=>{change(s=>({...s,nodes:s.nodes.map(n=>{if(n.id!==selected)return n;const next={...n,...patch};next.w=bounded(next.w,20,s.width);next.h=bounded(next.h,20,s.height);next.x=bounded(next.x,0,s.width-next.w);next.y=bounded(next.y,0,s.height-next.h);return next;})}));};
 const updateEdge=patch=>change(s=>({...s,edges:s.edges.map(e=>e.id===selected?{...e,...patch}:e)}));
 const remove=()=>{change(s=>({...s,nodes:s.nodes.filter(n=>n.id!==selected),edges:s.edges.filter(e=>e.id!==selected&&e.from!==selected&&e.to!==selected)}));setSelected(null);};
 const point=e=>{const r=svgRef.current.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*scene.width,y:(e.clientY-r.top)/r.height*scene.height};};
 const begin=(e,n,resize=false)=>{e.preventDefault();e.stopPropagation();setSelected(n.id);e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:n.id,start:point(e),node:copy(n),scene:copy(scene),resize,moved:false};};
 const move=e=>{const d=drag.current;if(!d)return;const p=point(e),dx=p.x-d.start.x,dy=p.y-d.start.y;d.moved||=Math.abs(dx)+Math.abs(dy)>1;setScene(s=>({...s,nodes:s.nodes.map(n=>n.id!==d.id?n:d.resize?{...n,w:bounded(d.node.w+dx,40,s.width-n.x),h:bounded(d.node.h+dy,40,s.height-n.y)}:{...n,x:bounded(d.node.x+dx,0,s.width-n.w),y:bounded(d.node.y+dy,0,s.height-n.h)})}));};
 const end=()=>{const finished=drag.current;if(finished?.moved){setHistory(h=>[...h.slice(-39),{scene:finished.scene,baseFigureId,proposalId}]);setFuture([]);}drag.current=null;};
 const keyMove=(e,n)=>{if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const delta=e.shiftKey?10:1;updateNode({x:n.x+(e.key==='ArrowRight'?delta:e.key==='ArrowLeft'?-delta:0),y:n.y+(e.key==='ArrowDown'?delta:e.key==='ArrowUp'?-delta:0)});}};
 const save=async()=>{try{const valid=validateScene(scene,catalog);saving.current=JSON.stringify(valid);const ok=await onTemplateEdit({action:'save-illustration',scene:valid,baseFigureId,proposalId,linkCurrentResearch});if(!ok)saving.current=null;}catch(e){saving.current=null;setError(e.message);}};
 const load=f=>{change(copy(f.scene));setBase(f.id);setProposal(f.proposalId??null);setSelected(null);};
 const exportFigure=async format=>{setError('');setExporting(true);try{
   const data={},ids=[...new Set(scene.nodes.filter(n=>n.type==='asset').map(n=>n.assetId))];await Promise.all(ids.map(async id=>{const a=catalog.assets.find(a=>a.id===id),r=await fetch(url(a));if(!r.ok)throw Error('素材读取失败，未导出缺图文件。');const b=await r.blob();data[id]=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('素材编码失败'));reader.readAsDataURL(b);});}));
   const svg=sceneSvg(scene,catalog,data,widthMm),filename=scene.title.replace(/[\\/:*?"<>|]/g,'-');
   if(format==='svg')download(`${filename}.svg`,svg,'image/svg+xml');
   else {const objectUrl=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();img.src=objectUrl;await img.decode();const c=document.createElement('canvas');c.width=Math.round(widthMm/25.4*300);c.height=Math.round(c.width*scene.height/scene.width);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const b=await new Promise(r=>c.toBlob(r,'image/png'));if(!b)throw Error('PNG 导出失败。');const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${filename}-300ppi-size.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);}finally{URL.revokeObjectURL(objectUrl);}}
   setNotice('已导出。请一并下载图注与素材署名，并按目标期刊核对最终尺寸。');
  }catch(e){setError(e.message);}finally{setExporting(false);}};
 const proposals=artifact.topicWorkspace?.figureProposals??[],latest=proposals.at(-1);
 const filtered=catalog?.assets.filter(a=>(category==='all'||a.category===category)&&(style==='all'||a.style===style)&&[a.name,a.englishName,...a.keywords].join(' ').toLowerCase().includes(query.toLowerCase().trim()))??[];
 const addRelation=()=>{if(!relation.from||relation.from===relation.to){setError('请选择两个不同元素。');return;}const e={...relation,id:uid(),label:'',quote:'',color:'#416d69'};change(s=>({...s,edges:[...s.edges,e]}));setSelected(e.id);};
 const introText=()=>{const w=artifact.topicWorkspace,outline=w?.outlines?.find(o=>o.id===w.confirmedOutlineId),writing=w?.writingWorkspaces?.[outline?.id];return Object.values(writing?.sections??{}).flatMap(s=>s.versions?.find(v=>v.id===s.activeVersionId)?.paragraphs?.map(p=>p.text)??[]).join('\n\n');};
 if(mode==='data')return <div><button onClick={()=>setMode('illustration')}>返回图像工作区</button><DataFigures {...props}/></div>;
 return <section className="figure-studio" aria-label="图像工作区">
  <header className="fs-heading"><div><small>科研素材与图稿</small><h2>图像工作区</h2><p>把研究逻辑变成可编辑的图，再打磨每一个细节。</p></div><button onClick={()=>setMode('data')}>数据图与流程图 <ArrowRight size={15}/></button></header>
  <div className="fs-document"><input aria-label="图稿名称" value={scene.title} maxLength={200} onChange={e=>change(s=>({...s,title:e.target.value}))}/><span>{scene.nodes.length} 个元素 · {scene.edges.length} 条关系</span><button disabled={disabled||!catalog} className="primary" onClick={save}><FloppyDisk size={17}/>保存版本</button><details className="fs-menu"><summary>导出与历史</summary><div><label>最终印刷宽度（mm）<input aria-label="最终印刷宽度" type="number" min="50" max="400" value={widthMm} onChange={e=>setWidthMm(Number(e.target.value))}/></label><p>SVG 保留文字与连线；PNG 按 300 ppi 所需像素输出。图像素材本身的清晰度仍取决于原图。</p><button disabled={!catalog||exporting} onClick={()=>exportFigure('svg')}>导出可编辑 SVG</button><button disabled={!catalog||exporting} onClick={()=>exportFigure('png')}>导出 PNG</button><button disabled={!catalog} onClick={()=>download(`${scene.title}-图注与署名.txt`,`${scene.title}\n\n${scene.caption}\n\n${figureCredits(scene,catalog)}\n\n关系来源\n${scene.edges.map(e=>`${e.label||edgeKinds[e.kind]}: ${e.quote||'手动关系，依据待补'}`).join('\n')}\n\n图稿依据\n${scene.sourceText}`,'text/plain')}>下载图注与素材署名</button><button onClick={()=>download('figure-scene.json',JSON.stringify(scene,null,2),'application/json')}>导出图稿结构</button><label>导入图稿结构<input aria-label="导入图稿结构" type="file" accept="application/json,.json" disabled={!catalog} onChange={async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>400000)throw Error('图稿结构文件不得超过 400 KB。');const imported=validateScene(JSON.parse(await f.text()),catalog);change({...imported,id:`drawing-${crypto.randomUUID()}`});setBase(null);setProposal(null);}catch(e){setError(e.message);}}}/></label><label><input type="checkbox" checked={linkCurrentResearch} onChange={e=>setLinkCurrentResearch(e.target.checked)}/>本图实际使用当前采用方案和结果，保存时关联</label><ExportEvidence projectId={project.id} title={scene.title} refs={figures.some(f=>f.id===baseFigureId&&JSON.stringify(f.scene)===JSON.stringify(scene))?[nestedRef('figure',artifact,null,null,baseFigureId)]:[]} draft={figures.some(f=>f.id===baseFigureId&&JSON.stringify(f.scene)===JSON.stringify(scene))?null:scene} files={[{name:`${scene.title}-图稿结构.json`,content:JSON.stringify(scene,null,2)},{name:'图注与来源.txt',content:scene.caption+'\n\n'+scene.sourceText}]}/><hr/><button onClick={()=>{change(emptyScene());setBase(null);setProposal(null);setSelected(null);}}>新建图稿（可撤销）</button>{figures.slice().reverse().map((f,i)=><button key={f.id} onClick={()=>load(f)}>{f.title} · {new Date(f.at).toLocaleString()} {f.id===baseFigureId?'· 当前底稿':''}</button>)}</div></details></div>
  {error&&<p className="fs-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="关闭错误">×</button></p>}{notice&&<p className="fs-notice" role="status">{notice}</p>}
  <div className="fs-layout"><aside className="fs-library"><h3>素材库 <span>{catalog?.assets.length??'…'}</span></h3><label className="fs-search"><MagnifyingGlass size={17}/><input aria-label="搜索科研素材" value={query} placeholder="搜索：小鼠、DNA、胃…" onChange={e=>setQuery(e.target.value)}/></label><select aria-label="素材类别" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">全部类别</option>{catalog?.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select aria-label="素材风格" value={style} onChange={e=>setStyle(e.target.value)}><option value="all">全部风格</option><option value="servier">Servier · 医学矢量</option><option value="community">社区 · 简洁矢量</option><option value="workbench">工作台 · 定制插图</option></select><div className="fs-assets">{filtered.map(a=><button key={a.id} className="fs-asset" onClick={()=>add('asset',a)} title={`添加${a.name} · ${a.license.id}`} aria-label={`添加素材：${a.name}`}><img src={url(a)} alt="" loading="lazy"/><span>{a.name}</span><small>{a.format==='svg'?'SVG': 'AI · PNG'}</small></button>)}</div>{!filtered.length&&catalog&&<p>没有匹配素材。可以添加文字占位，或更换关键词。</p>}<a className="fs-pack" href="/api/scientific-assets/pack" download><DownloadSimple size={15}/>下载完整素材包</a><small className="fs-license-note">素材保留原作者和逐项许可；署名随图稿导出。AI 素材为待核对示意。</small></aside>
  <div className="fs-center"><div className="fs-toolbar"><div><button title="撤销" aria-label="撤销图稿修改" disabled={!history.length} onClick={undo}><ArrowCounterClockwise size={18}/></button><button title="重做" aria-label="重做图稿修改" disabled={!future.length} onClick={redo}><ArrowClockwise size={18}/></button></div><div><button onClick={()=>add('text')}><TextT size={17}/>文字</button><button onClick={()=>add('box')}><Shapes size={17}/>区室</button></div><div><select aria-label="整理布局" value={layout} onChange={e=>setLayout(e.target.value)}><option value="horizontal">横向</option><option value="vertical">纵向</option><option value="grid">网格</option></select><button disabled={!scene.nodes.length} onClick={()=>change(arrangeScene(scene,layout))}>整理</button></div></div>
   {!scene.nodes.length&&<div className="fs-templates"><span>从基础结构开始</span>{[['signal','信号传导'],['interaction','细胞互作'],['experiment','实验流程']].map(([k,v])=><button key={k} onClick={()=>{change(sceneTemplate(k));setBase(null);setProposal(null);}}>{v}</button>)}</div>}
   <div className="fs-canvas-wrap"><svg ref={svgRef} className="fs-canvas" viewBox={`0 0 ${scene.width} ${scene.height}`} aria-label="可编辑科研图稿" role="group" onPointerMove={move} onPointerUp={end} onPointerCancel={end} onPointerDown={()=>setSelected(null)}>
    <defs><marker id="fs-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="context-stroke"/></marker><marker id="fs-inhibit" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M9 0V10" stroke="context-stroke" strokeWidth="2"/></marker></defs>
    <rect width={scene.width} height={scene.height} fill="white"/>
    {scene.nodes.filter(n=>n.type==='box').map(n=><rect key={`bg-${n.id}`} x={n.x} y={n.y} width={n.w} height={n.h} rx="12" fill={n.fill} stroke={n.color} strokeWidth="1.5"/>)}
    {scene.edges.map(e=>{const p=connector(scene,e);if(!p)return null;return <g key={e.id} tabIndex={0} role="button" aria-label={`选择关系：${e.label||edgeKinds[e.kind]}`} onFocus={()=>setSelected(e.id)} onPointerDown={v=>{v.stopPropagation();setSelected(e.id);}}><line {...p} stroke="transparent" strokeWidth="20"/><line {...p} stroke={e.color} strokeWidth={selected===e.id?4:2.3} strokeDasharray={e.kind==='hypothesis'?'7 5':undefined} markerEnd={e.kind==='association'?undefined:e.kind==='inhibition'?'url(#fs-inhibit)':'url(#fs-arrow)'}/><text x={(p.x1+p.x2)/2} y={(p.y1+p.y2)/2-10} fontSize="18" fill={e.color} textAnchor="middle">{e.label}</text></g>;})}
    {scene.nodes.map(n=>{const a=catalog?.assets.find(a=>a.id===n.assetId),lines=nodeLabelLines(n.label,Math.max(3,n.w/n.fontSize-1)),labelHeight=lines.length*n.fontSize*1.25;return <g key={n.id} role="button" aria-label={`选择元素：${n.label}`} tabIndex={0} onFocus={()=>setSelected(n.id)} transform={`translate(${n.x} ${n.y})`} onPointerDown={e=>begin(e,n)} onKeyDown={e=>keyMove(e,n)} style={{cursor:'move'}}><rect width={n.w} height={n.h} fill="transparent" stroke={selected===n.id?'#34867a':'none'} strokeWidth="2" strokeDasharray="6 4"/>{a&&<image href={url(a)} width={n.w} height={Math.max(20,n.h-labelHeight-5)} preserveAspectRatio="xMidYMid meet" transform={n.flip?`translate(${n.w} 0) scale(-1 1)`:undefined}/>}<text x={n.w/2} y={n.type==='asset'?n.h-labelHeight+n.fontSize:n.type==='box'?n.fontSize+14:n.fontSize} fill={n.color} fontSize={n.fontSize} textAnchor="middle" pointerEvents="none">{lines.map((l,i)=><tspan key={i} x={n.w/2} dy={i?n.fontSize*1.25:0}>{l}</tspan>)}</text>{selected===n.id&&<rect x={n.w-7} y={n.h-7} width="14" height="14" fill="#34867a" cursor="nwse-resize" onPointerDown={e=>begin(e,n,true)}/>}</g>;})}
    {!scene.nodes.length&&<text x="600" y="385" textAnchor="middle" fill="#82918a" fontSize="25">从左侧添加素材，或在下方整理文字关系</text>}
   </svg></div><div className="fs-canvas-caption"><span>{scene.width} × {scene.height} · 拖动排版，选中后方向键微调</span><span>解释性图稿</span></div>
   <details className="fs-compose" open={!scene.nodes.length}><summary>从文字到图稿 <span>模型整理关系 · 可手动继续</span></summary><label>本图的依据与表达内容<textarea aria-label="图稿依据文字" rows="4" value={scene.sourceText} maxLength={24000} placeholder="写清研究对象、细胞或分子，以及谁影响谁。模型仅整理这段文字中的关系。" onChange={e=>change(s=>({...s,sourceText:e.target.value}))}/></label><div className="fs-actions"><button disabled={!introText()} onClick={()=>change(s=>({...s,sourceText:introText().slice(0,24000)}))}>带入已存正文</button><button className="primary" disabled={disabled||!catalog||!scene.sourceText.trim()} onClick={()=>onRun('figure-compose',{accessIds:[],text:scene.sourceText,figureOptions:{title:scene.title}})}>整理关系并提出排版</button></div><small>使用工作台已配置的文字模型；只发送本图文字、专题名称和素材目录。手工组装无需模型账号。</small>{task?.mode==='figure-compose'&&<p role="status">{task.progress}</p>}{latest&&<div className="fs-proposal"><strong>排版候选</strong><p>{latest.explanation}</p><p>{latest.scene.nodes.length} 个元素 · {latest.scene.edges.length} 条关系</p><button onClick={()=>{change({...copy(latest.scene),id:`drawing-${crypto.randomUUID()}`});setBase(null);setProposal(latest.id);setSelected(null);}}>应用候选到画布</button><details><summary>核对候选中的关系</summary>{latest.scene.edges.map(e=><p key={e.id}>{latest.scene.nodes.find(n=>n.id===e.from)?.label} → {latest.scene.nodes.find(n=>n.id===e.to)?.label} · {edgeKinds[e.kind]}<br/>依据：{e.quote}</p>)}</details></div>}</details>
  </div><aside className="fs-inspector"><h3>{node?'调整元素':edge?'调整关系':'图稿设置'}</h3>{node?<><label>文字<input aria-label="元素文字" value={node.label} maxLength={400} onChange={e=>updateNode({label:e.target.value})}/></label><div className="fs-fields">{[['x','横坐标'],['y','纵坐标'],['w','宽度'],['h','高度'],['fontSize','字号']].map(([k,l])=><label key={k}>{l}<input aria-label={`元素${l}`} type="number" min={k==='fontSize'?10:0} max={k==='fontSize'?80:2400} value={Math.round(node[k]*10)/10} onChange={e=>{const v=Number(e.target.value);if(Number.isFinite(v))updateNode({[k]:k==='fontSize'?bounded(v,10,80):v});}}/></label>)}</div><label>文字与边框<input aria-label="元素颜色" type="color" value={node.color} onChange={e=>updateNode({color:e.target.value})}/></label>{node.type==='box'&&<label>区室填色<input type="color" value={node.fill} onChange={e=>updateNode({fill:e.target.value})}/></label>}{asset&&<><button onClick={()=>updateNode({flip:!node.flip})}>水平翻转</button><div className="fs-provenance"><strong>{asset.name}</strong><p>{asset.source.author} · {asset.license.id}</p>{asset.source.url&&<a href={asset.source.url} target="_blank" rel="noreferrer">查看素材来源</a>}<a href={url(asset)} download={`${asset.id}.${asset.format}`}>下载原始素材</a><p>{asset.review.note}</p></div></>}<div className="fs-actions"><button onClick={()=>change(s=>({...s,nodes:[...s.nodes.filter(n=>n.id!==node.id),node]}))}>置于顶层</button><button onClick={()=>change(s=>({...s,nodes:[node,...s.nodes.filter(n=>n.id!==node.id)]}))}>移到底层</button></div></>:edge?<><label>关系文字<input aria-label="关系文字" value={edge.label} maxLength={180} onChange={e=>updateEdge({label:e.target.value})}/></label><label>关系类型<select aria-label="关系类型" value={edge.kind} onChange={e=>updateEdge({kind:e.target.value})}>{Object.entries(edgeKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>依据原句<textarea aria-label="关系依据" value={edge.quote} maxLength={2000} rows="4" onChange={e=>updateEdge({quote:e.target.value})}/></label><button onClick={()=>updateEdge({from:edge.to,to:edge.from})}>反转方向</button><label>线条颜色<input type="color" value={edge.color} onChange={e=>updateEdge({color:e.target.value})}/></label></>:<p className="fs-hint">选择画布中的素材、文字或连线，在这里调整。每条关系都可以保留依据。</p>}{(node||edge)&&<button className="fs-remove" onClick={remove}><Trash size={15}/>删除选中元素</button>}
   <details className="fs-relations" open><summary>添加关系</summary>{[['from','起点'],['to','终点']].map(([k,l])=><label key={k}>{l}<select aria-label={`关系${l}`} value={relation[k]} onChange={e=>setRelation(v=>({...v,[k]:e.target.value}))}><option value="">选择元素</option>{scene.nodes.map(n=><option value={n.id} key={n.id}>{n.label||'无文字元素'}</option>)}</select></label>)}<select aria-label="新增关系类型" value={relation.kind} onChange={e=>setRelation(v=>({...v,kind:e.target.value}))}>{Object.entries(edgeKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button disabled={!relation.from||!relation.to||scene.edges.length>=100} onClick={addRelation}><Plus size={15}/>添加连线</button></details>
   <details><summary>图注与出版检查</summary><label>图注<textarea aria-label="图注" rows="4" maxLength={6000} value={scene.caption} onChange={e=>change(s=>({...s,caption:e.target.value}))}/></label><p>当前为待审阅图稿。投稿前核对机制方向、物种和细胞身份、证据、署名及目标期刊规格。</p><p>最小文字约 {((Math.min(18,...scene.nodes.map(n=>n.fontSize))*widthMm/scene.width)*72/25.4).toFixed(1)} pt（按 {widthMm} mm 宽）。可用右侧字号放大。</p>{scene.edges.filter(e=>!e.quote.trim()).length>0&&<p>{scene.edges.filter(e=>!e.quote.trim()).length} 条手动关系尚未附依据。</p>}</details>
  </aside></div>
 </section>;
}
