import {useEffect,useRef,useState} from 'react';
import {CaretLeft,CaretRight,MagnifyingGlass,Minus,Plus,FilePdf} from '@phosphor-icons/react';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import {api} from './ui.jsx';
export function FulltextImport({project,paper,onRefresh,artifact,disabled,onEdit}){
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[zotero,setZotero]=useState(null);
  const acquire=async(file)=>{setBusy(true);setError('');try{
    const body={artifactId:artifact.id,baseTemplateVersion:project.templateLibrary.version};
    if(file){if(file.size>25*1024*1024)throw new Error('PDF 不得超过 25 MB。');body.filename=file.name;body.base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>resolve(String(r.result).split(',')[1]);r.readAsDataURL(file);});}
    await api.request(`/api/projects/${project.id}/templates/${paper.id}/fulltext`,{method:'POST',body});await onRefresh();
  }catch(e){setError(e.message||'原文导入未完成，请重试。');}finally{setBusy(false);}};
  return <div className="fulltext-import"><div><button disabled={busy||disabled} className={!paper.document?'primary':''} onClick={()=>acquire()}>{busy?'正在获取与解析…':paper.document?'重新获取全文':'获取开放全文'}</button><label className="pdf-upload">导入 PDF<input aria-label="导入模板 PDF" type="file" accept="application/pdf,.pdf" disabled={busy||disabled} onChange={e=>{const f=e.target.files[0];if(f)acquire(f);e.target.value='';}}/></label><button disabled={busy} onClick={async()=>{try{setZotero(await api.request(`/api/projects/${project.id}/templates/${paper.id}/zotero`));}catch(e){setError(e.message);}}}>连接 Zotero</button></div>{paper.document?.readable&&!paper.document.complete&&<p>请查阅并确认此 PDF 包含论文完整正文。<button disabled={disabled||busy} onClick={()=>onEdit?.({action:'confirm-document',paperId:paper.id,documentHash:paper.document.sha256})}>已核对正文完整</button></p>}{error&&<p role="alert">{error}</p>}{zotero&&<div><p>{zotero.message}</p>{zotero.attachments?.filter(a=>a.contentType==='application/pdf').map(a=><p key={a.key}><a href={a.href}>{a.title} · 在 Zotero 打开 ↗</a></p>)}<small>可将 Zotero 中的原文 PDF 导入此处，保留分页供对照阅读。</small></div>}</div>;
}
export function PdfReader({project,paper,page=1,onPage,onRefresh,artifact,disabled,anchor,onEdit}){
  const canvas=useRef(),container=useRef(),[pdf,setPdf]=useState(null),[zoom,setZoom]=useState(1),[width,setWidth]=useState(600),[error,setError]=useState(''),[textView,setTextView]=useState(false),[query,setQuery]=useState(''),[selectedText,setSelectedText]=useState('');
  const doc=paper?.document,url=doc?`/api/projects/${project.id}/templates/${paper.id}/pdf?version=${doc.sha256}`:null;
  useEffect(()=>{if(!container.current)return;const observer=new ResizeObserver(entries=>setWidth(Math.max(240,entries[0].contentRect.width-32)));observer.observe(container.current);return()=>observer.disconnect();},[]);
  useEffect(()=>{setPdf(null);setError('');if(!url)return;let alive=true,task;import('pdfjs-dist').then(({getDocument,GlobalWorkerOptions})=>{if(!alive)return;GlobalWorkerOptions.workerSrc=workerUrl;task=getDocument({url,isEvalSupported:false});return task.promise;}).then(d=>{if(alive&&d)setPdf(d);}).catch(()=>{if(alive)setError('PDF 显示未完成，可重试或查看分页文字。');});return()=>{alive=false;void task?.destroy();};},[url]);
  useEffect(()=>{if(!pdf||textView)return;let cancelled=false,render;
    pdf.getPage(Math.min(page,pdf.numPages)).then(p=>{if(cancelled)return;const base=p.getViewport({scale:1}),viewport=p.getViewport({scale:width/base.width*zoom}),c=canvas.current;if(!c)return;const ratio=Math.min(devicePixelRatio||1,2);c.width=viewport.width*ratio;c.height=viewport.height*ratio;c.style.width=`${viewport.width}px`;c.style.height=`${viewport.height}px`;render=p.render({canvasContext:c.getContext('2d'),viewport,transform:[ratio,0,0,ratio,0,0]});return render.promise;}).catch(e=>{if(e.name!=='RenderingCancelledException'&&!cancelled)setError('本页暂未显示，可查看分页文字或重新打开。');});return()=>{cancelled=true;render?.cancel();};},[pdf,page,zoom,width,textView]);
  const savePassage=async()=>{const offset=content.indexOf(selectedText);if(offset<0||content.indexOf(selectedText,offset+1)>=0)return;const start=doc.pages.slice(0,page-1).reduce((n,p)=>n+p.text.length+2,0)+offset;await onEdit?.({action:'select-passage',paperId:paper.id,textVersion:paper.textVersion,start,end:start+selectedText.length});setSelectedText('');};
  const matches=doc?.pages.filter(p=>query.trim()&&p.text.toLowerCase().includes(query.trim().toLowerCase()))??[],content=doc?.pages.find(p=>p.number===page)?.text??'';
  return <section className="pdf-reader" ref={container} aria-label="模板 PDF 原文"><header><strong><FilePdf size={20}/>模板原文</strong>{doc&&<><button aria-label="原文上一页" disabled={page<=1} onClick={()=>onPage(page-1)}><CaretLeft/></button><select aria-label="PDF 页码" value={page} onChange={e=>onPage(Number(e.target.value))}>{doc.pages.map(p=><option key={p.number} value={p.number}>第 {p.number} / {doc.pageCount} 页</option>)}</select><button aria-label="原文下一页" disabled={page>=doc.pageCount} onClick={()=>onPage(page+1)}><CaretRight/></button><button aria-label="缩小 PDF" disabled={zoom<=.6} onClick={()=>setZoom(z=>Math.max(.6,z-.2))}><Minus/></button><span>{Math.round(zoom*100)}%</span><button aria-label="放大 PDF" disabled={zoom>=2} onClick={()=>setZoom(z=>Math.min(2,z+.2))}><Plus/></button><button aria-pressed={textView} onClick={()=>setTextView(v=>!v)}>{textView?'PDF':'文字'}</button></>}</header>
  {paper?<><details className="pdf-source-tools" open={!doc||!doc.complete}><summary>{paper.title}</summary><FulltextImport project={project} artifact={artifact} paper={paper} onEdit={onEdit} onRefresh={onRefresh} disabled={disabled}/>{doc&&!doc.readable&&<p>部分页未提取到足够文字，暂不能用于全文分析。请提供可检索文字的 PDF。</p>}</details>{doc&&<div className="pdf-search"><MagnifyingGlass size={16}/><input type="search" aria-label="检索 PDF 全文" placeholder="检索原文" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<span>{matches.length} 页</span>}{matches.map(p=><button key={p.number} onClick={()=>{onPage(p.number);setTextView(true);}}>P{p.number}</button>)}</div>}{anchor&&<blockquote className="pdf-anchor"><small>修改依据 · 第 {anchor.page} 页</small>{anchor.quote}</blockquote>}{error&&<p role="alert">{error}</p>}<div className="pdf-pages">{doc?(textView?<div><pre className="pdf-text" onMouseUp={()=>{const text=window.getSelection()?.toString().trim()??'';setSelectedText(text.length>=12&&text.length<=16000&&content.includes(text)?text:'');}}>{content}</pre>{selectedText&&<button disabled={disabled} onClick={savePassage}>将所选原文用于本段修订</button>}</div>:<canvas ref={canvas} aria-label={`原文 PDF 第 ${page} 页`}/>):<div className="pdf-empty"><FilePdf size={40}/><h2>阅读完整原文</h2><p>获取开放全文，或导入已取得的 PDF。</p><p>原文获取后保留分页；完成全文分析后，可据此提出正文修改建议。</p>{paper.text&&<details><summary>查看当前已存文本 · {paper.level==='abstract'?'摘要':'片段'}</summary><p style={{whiteSpace:'pre-wrap',textAlign:'left'}}>{paper.text}</p></details>}</div>}</div></>:<div className="pdf-empty"><p>请从批注中选择模板文献。</p></div>}</section>;
}
