import {FulltextImport} from './PdfReader.jsx';
import {TemplateReader} from './TemplateReader.jsx';
import {useState,useEffect} from 'react';
import {articleTypes,templateSelection,templateStudy,latestTemplateRecommendation,hasFulltext,templateReady,completeTemplateStudy} from '../../shared/research-templates.mjs';
import './research-templates.css';
const levelNames={title:'题名',abstract:'摘要',fulltext:'全文',excerpt:'原文片段'};
export function ResearchTemplates({project,artifact,disabled,onEdit,onRun,onReadZotero,onRefresh,task,recipient}) {
  const [reader,setReader]=useState(false);
  const selection=templateSelection(project,artifact),paper=selection.paper,library=project.templateLibrary,rec=latestTemplateRecommendation(project,artifact.id),study=project.templateLibrary?.studies?.findLast(s=>s.artifactId===artifact.id&&s.paperId===paper?.id&&s.textVersion===paper?.textVersion&&s.documentHash===paper?.document?.sha256);
  const cacheKey=`rw2:template-input:${project.id}:${artifact.id}`;
  const [cached]=useState(()=>{try{return JSON.parse(localStorage.getItem(cacheKey))??{};}catch{return {};}});
  const question=project.researchItems?.[artifact.branchQuestion?.itemId]?.revisions.find(r=>r.id===artifact.branchQuestion.revisionId)?.text;
  const [topic,setTopic]=useState(cached.topic??rec?.topic??question??project.goal??project.name),[articleType,setType]=useState(cached.articleType??rec?.articleType??(artifact.kind==='brief'?'review':'original')),[journal,setJournal]=useState(cached.journal??rec?.targetJournal??''),[existing,setExisting]=useState('');
  useEffect(()=>{localStorage.setItem(cacheKey,JSON.stringify({topic,articleType,journal}));},[topic,articleType,journal,cacheKey]);
  const recIds=rec?.candidates.map(c=>c.paperId)??[],extra=Object.values(library?.papers??{}).filter(p=>p.sourceAccessId&&!recIds.includes(p.id));
  return <div className="template-panel"><p className="template-intro">关联领域分析、研究设计与正文修订所用的模板文献。</p>
    <div className="template-current"><span className="template-eyebrow">当前主模板{selection.inherited?' · 来自上一步':''}</span>{paper?<><h3>{paper.title}</h3><small>{paper.year} · {paper.journal}</small><p>{levelNames[paper.level]}{paper.location?` · ${paper.location}`:''}</p><button className="template-reader-open primary" onClick={()=>setReader(true)}>阅读模板原文</button><button disabled={disabled} onClick={()=>onEdit({action:'select',paperId:null})}>本阶段暂不用模板</button></>:<p>尚未选择主模板；正文生成与模板选择可分别进行。</p>}</div>
    <details className="template-find" open={!paper}><summary>推荐与选择模板</summary><label>当前领域或专题<textarea aria-label="模板研究范围" value={topic} onChange={e=>setTopic(e.target.value)} rows={3}/></label><div className="template-fields"><label>文章类型<select aria-label="模板文章类型" value={articleType} onChange={e=>setType(e.target.value)}>{Object.entries(articleTypes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>目标期刊（可选）<input aria-label="模板目标期刊" value={journal} onChange={e=>setJournal(e.target.value)} placeholder="例如 Nature Reviews…"/></label></div><button className="primary" disabled={disabled||!topic.trim()} onClick={()=>onRun('template-recommend',{accessIds:[],text:'推荐当前专题最新、权威且适合学习的同类型模板文献，供我确认。',templateOptions:{topic,articleType,targetJournal:journal}})}>{task?.mode==='template-recommend'?'正在推荐…':'推荐模板文献'}</button><p className="template-help">结合专题契合、文章类型、期刊与新近程度推荐，最多三篇。影响因子未经核验时不参与数值排名。</p>{rec&&<small>{rec.searchWindow} · 已比较 {rec.retrievedCount} 篇候选</small>}
    {rec&&!rec.candidates.length&&<p>本次未找到合适模板，可调整专题、文章类型或目标期刊。</p>}
    <ol className="template-candidates">{rec?.candidates.map((c,i)=>{const p=library.papers[c.paperId];return <li key={p.id}><span className="template-rank">{i+1}</span><h3><a href={p.url} target="_blank" rel="noreferrer">{p.title}</a></h3><small>{p.year} · {p.journal} · {levelNames[p.level]}</small><p>{c.fit}</p><p><b>学习重点</b> {c.learn}</p><details><summary>推荐判断与取舍</summary><p>{c.quality}</p><p>{c.tradeoff}</p><small>影响因子：未核验</small></details><button className={paper?.id===p.id?'':'primary'} disabled={disabled||paper?.id===p.id} onClick={()=>onEdit({action:'select',paperId:p.id})}>{paper?.id===p.id?'已选为主模板':'确认作为主模板'}</button></li>;})}</ol>
    <details><summary>从已有文献中选择</summary><label>已保存的文献<select aria-label="已有模板文献" value={existing} onChange={e=>setExisting(e.target.value)}><option value="">选择一篇文献</option>{artifact.draft.sourceAccessIds.map(id=><option key={id} value={id}>{project.sources[project.accesses[id]?.sourceId]?.title}</option>)}</select></label><button disabled={disabled||!existing} onClick={()=>onEdit({action:'add-existing',accessId:existing})}>加入模板候选</button>{extra.map(p=><div className="template-existing" key={p.id}><p>{p.title}</p><button disabled={disabled||paper?.id===p.id} onClick={()=>onEdit({action:'select',paperId:p.id})}>{paper?.id===p.id?'已选为主模板':'确认作为主模板'}</button></div>)}</details></details>
    {paper&&reader&&<TemplateReader project={project} artifact={artifact} paper={paper} selection={selection} disabled={disabled} onClose={()=>setReader(false)} onEdit={onEdit} onRefresh={onRefresh} onReadZotero={onReadZotero}/>}
    {paper&&<><FulltextImport project={project} artifact={artifact} paper={paper} onEdit={onEdit} onRefresh={onRefresh} disabled={disabled}/><TemplateText key={paper.id} paper={paper} disabled={disabled} onEdit={onEdit}/><div className="template-study"><h3>论证结构与写作特征</h3><p>分析科学命题、证据组织及表达方式，提炼可用于本研究的写作特征。</p><button disabled={disabled||!hasFulltext(paper)} onClick={()=>onRun('template-study',{accessIds:[],text:'阅读已确认模板，归纳可迁移的论证结构与写作特点。',templateOptions:{articleType,topic}})}>{study?'查看全文分析':'分析完整原文'}</button>{study&&<><p className="template-scope">{study.scope}</p>{study.features.map((f,i)=><section key={i}><h4>{f.aspect}</h4><p>{f.observation}</p><p><b>应用方式</b> {f.application}</p></section>)}</>}</div></>}
    <p className="template-help">主模板由研究者确认。模板用于结构与表达参照，科学主张仍须独立核对依据。{recipient&&`分析使用已配置模型 ${recipient}。`}</p>
  </div>;
}
function TemplateText({paper,disabled,onEdit}) {
  const key=`rw2:template-text:${paper.id}`,[cached]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??{};}catch{return {};}}),[text,setText]=useState(cached.text??''),[level,setLevel]=useState(cached.level??'excerpt'),[location,setLocation]=useState(cached.location??'');
  useEffect(()=>{localStorage.setItem(key,JSON.stringify({text,level,location}));},[key,text,level,location]);
  return <details className="template-text"><summary>原文与读取范围 · {levelNames[paper.level]}</summary><p className="template-raw">{paper.text||'尚无摘要或原文。'}</p><a href={paper.url} target="_blank" rel="noreferrer">打开文献页 ↗</a><p>原文用于分析段落结构与表达；仅有摘要时，分析限于摘要。</p><label>补充模板原文<textarea aria-label="模板原文" value={text} onChange={e=>setText(e.target.value)} rows={6} placeholder="粘贴你已取得的正文或目标段落…"/></label><label>读取范围<select aria-label="模板读取范围" value={level} onChange={e=>setLevel(e.target.value)}><option value="excerpt">原文片段</option><option value="fulltext">全文</option></select></label><label>原文位置<input aria-label="模板原文位置" value={location} onChange={e=>setLocation(e.target.value)} placeholder="例如 Introduction 第2—4段"/></label><button disabled={disabled||!text.trim()||!location.trim()} onClick={async()=>{if(await onEdit({action:'save-text',paperId:paper.id,text,level,location})){setText('');localStorage.removeItem(key);}}}>保存模板原文</button></details>;
}
export function ParagraphOptimization({project,artifact,outline,section,version,paragraph,disabled,onRun,onEdit,onTemplates,onAnchor}) {
  const selection=templateSelection(project,artifact),paper=selection.paper,proposal=project.templateLibrary?.optimizations.findLast(o=>o.artifactId===artifact.id&&o.writingVersionId===version.id&&o.paragraphId===paragraph.id&&o.paperId===paper?.id&&o.textVersion===(paper?.textVersion??1)&&o.focusText===(selection.focus?.textVersion===paper?.textVersion?selection.focus.text:null));
  const ready=templateReady(project,paper,artifact),fullStudy=completeTemplateStudy(project,paper,artifact);
  const [choices,setChoices]=useState({});
  useEffect(()=>setChoices({}),[proposal?.id]);
  return <details className="paragraph-optimization" open={Boolean(proposal)}><summary>按模板逐段优化{proposal?' · 修改建议已就绪':''}</summary>{paper?<><p className="template-use">主模板：{paper.title}<small>{selection.focus?.textVersion===paper.textVersion?'已选原文片段':levelNames[paper.level]} · 学习表达与论证组织</small><button onClick={onTemplates}>查看模板与原文</button></p>{selection.focus?.textVersion===paper.textVersion&&<details className="template-focus-preview"><summary>本段采用的模板片段</summary><p>{selection.focus.text}</p></details>}<button disabled={disabled||!ready} onClick={()=>onRun('template-optimize',{accessIds:[],text:'对照已确认模板，诊断并逐句优化当前段落，保持事实与证据边界。',templateOptions:{outlineId:outline.id,sectionId:section.id,writingVersionId:version.id,paragraphId:paragraph.id}})}>{proposal?'重新提出修改建议':'分析并提出修改建议'}</button>{!ready&&<p>取得完整 PDF 并完成全文分析后，可生成有原文依据的修改建议。</p>}</>:<p>选择一篇主模板，再比较本段的论证与表达。<button onClick={onTemplates}>选择模板文献</button></p>}
    {proposal&&ready&&proposal.studyId===fullStudy?.id&&<div className="optimization-proposal"><p className="optimization-diagnosis">{proposal.diagnosis}</p><details><summary>本次采用的模板写作特点</summary><p>{proposal.study.scope}</p>{proposal.study.features.map((f,i)=><p key={i}><b>{f.aspect}</b> · {f.observation} {f.application}</p>)}</details>{proposal.suggestions.map((s,i)=><fieldset key={s.id}><legend>{i+1}. {s.issue}</legend><div className="proposal-anchors">{s.principleIds?.map(id=>{const f=fullStudy.features.find(f=>f.id===id);return f&&<details key={id}><summary>修改依据 · {f.aspect}</summary><p>{f.observation}</p><p>{f.application}</p><small>{f.boundary}</small>{f.anchors.map((a,i)=><button key={i} onClick={()=>onAnchor?onAnchor(a):onTemplates()}>原文第 {a.page} 页 · {a.quote.slice(0,60)}…</button>)}</details>;})}</div><small>原句</small><blockquote>{s.before}</blockquote><label className="keep-original"><input type="radio" name={`${proposal.id}-${s.id}`} checked={!choices[s.id]} onChange={()=>setChoices(c=>({...c,[s.id]:null}))}/>保留原句</label>{s.options.map((o,j)=><label className="optimization-option" key={o.id}><input type="radio" name={`${proposal.id}-${s.id}`} checked={choices[s.id]===o.id} onChange={()=>setChoices(c=>({...c,[s.id]:o.id}))}/><span><b>方案 {j+1}</b><p className="academic-paragraph">{o.text}</p><span>{o.reason}</span><small>{o.useWhen}</small></span></label>)}</fieldset>)}<button className="primary" disabled={disabled||!Object.values(choices).some(Boolean)} onClick={()=>onEdit({action:'apply-optimization',optimizationId:proposal.id,choices:Object.entries(choices).filter(([,v])=>v).map(([suggestionId,optionId])=>({suggestionId,optionId}))})}>应用所选修改</button><small className="template-help">形成新的正文版本，原稿可回看；修改后重新核对依据。</small></div>}
  </details>;
}
