import {FigureWorkspace} from './FigureWorkspace.jsx';
import {PriorityRevision} from './RevisionTools.jsx';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,DownloadSimple,BookOpen,NotePencil,X} from '@phosphor-icons/react';
import {PdfReader} from './PdfReader.jsx';
import {SectionWriter} from './TopicWritingWorkbench.jsx';
import {writingSections,currentSectionVersion,manuscriptSnapshot,manuscriptMarkdown,manuscriptHtml} from '../../shared/topic-writing.mjs';
import {templateSelection,templateReady,hasFulltext} from '../../shared/research-templates.mjs';
import {download} from './ui.jsx';
import './revision-workspace.css';
const dimensions={design:'研究设计思路',logic:'论证逻辑',language:'语言特点'};
export function RevisionWorkspace(props){
  const {project,artifact,outline,onClose,onTemplates,onRun,onEdit,onTemplateEdit,onRefresh,disabled,task,operationError}=props;
  const dialog=useRef(),sections=writingSections(outline),workspace=artifact.topicWorkspace.writingWorkspaces?.[outline.id];
  const key=`rw2:revision:${project.id}:${outline.id}`;
  const [cached]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??{};}catch{return {};}});
  const [mode,setMode]=useState(cached.mode??'compare'),[sectionId,setSection]=useState(cached.sectionId??workspace?.activeSectionId??sections[0]?.id),[page,setPage]=useState(cached.page??1),[anchor,setAnchor]=useState(null),[showSource,setShowSource]=useState(true),[tab,setTab]=useState('design'),[factSource,setFactSource]=useState(null),[tool,setTool]=useState(null),[showFactPdf,setShowFactPdf]=useState(false);
  const paper=templateSelection(project,artifact).paper,study=project.templateLibrary?.studies?.findLast(s=>s.artifactId===artifact.id&&s.paperId===paper?.id&&s.textVersion===paper?.textVersion&&s.documentHash===paper?.document?.sha256),ready=templateReady(project,paper,artifact),section=sections.find(s=>s.id===sectionId)??sections[0],saved=workspace?.sections[section?.id],version=currentSectionVersion(saved);
  useEffect(()=>{const d=dialog.current;d.showModal();return()=>d.close();},[]);
  useEffect(()=>{try{localStorage.setItem(key,JSON.stringify({mode,sectionId,page,paperId:paper?.id,textVersion:paper?.textVersion}));}catch{}},[key,mode,sectionId,page,paper?.id,paper?.textVersion]);
  const lastDocument=useRef({id:cached.paperId,version:cached.textVersion});
  useEffect(()=>{if(lastDocument.current.id!==paper?.id||lastDocument.current.version!==paper?.textVersion){setPage(1);setAnchor(null);}lastDocument.current={id:paper?.id,version:paper?.textVersion};},[paper?.id,paper?.textVersion]);
  const locate=a=>{setFactSource(null);setShowFactPdf(false);setAnchor(a);setPage(a.page);setShowSource(true);};
  const factPaper=factSource&&Object.values(project.templateLibrary?.papers??{}).find(p=>hasFulltext(p)&&(factSource.source?.doi&&p.doi?.toLowerCase()===factSource.source.doi.toLowerCase()||factSource.source?.pmid&&String(p.pmid)===String(factSource.source.pmid)));
  const exportDraft=(html=false)=>{const m=manuscriptSnapshot(outline,workspace);download(`${outline.title}-正文.${html?'html':'md'}`,html?manuscriptHtml(m):manuscriptMarkdown(m),html?'text/html':'text/markdown');};
  const template=()=>{onClose();onTemplates();};
  return <dialog className={`revision-workspace revision-${mode} ${showSource?'':'source-collapsed'} ${tool==='figures'?'revision-figure-tool':''}`} ref={dialog} onCancel={e=>{e.preventDefault();onClose();}} aria-label="正文修订工作区">
    <header className="revision-topbar"><button onClick={onClose}><ArrowLeft size={17}/>返回工作台</button><strong>正文修订</strong><nav aria-label="阅读与修订流程"><button aria-current={!tool&&mode==='compare'?'step':undefined} onClick={()=>{setTool(null);setMode('compare');setShowSource(true);}}><BookOpen size={16}/>1 并排精读</button><button aria-current={!tool&&mode==='edit'?'step':undefined} onClick={()=>{setTool(null);setMode('edit');}}><NotePencil size={16}/>2 正文精修</button></nav><button className="primary" onClick={()=>exportDraft(true)}><DownloadSimple size={17}/>导出正文</button></header>
    <div className="revision-toolbar"><label>章节<select aria-label="修订章节" value={section.id} onChange={e=>setSection(e.target.value)}>{sections.map(s=><option key={s.id} value={s.id}>{s.number} {s.heading}</option>)}</select></label><span>{saved?.completedVersionId===version?.id?'本版已审阅':'当前正文'}</span><div className="revision-tools"><button aria-pressed={tool==='priority'} onClick={()=>setTool(t=>t==='priority'?null:'priority')}>重点章节</button><button aria-pressed={tool==='figures'} onClick={()=>setTool(t=>t==='figures'?null:'figures')}>科研作图</button><button onClick={template}>更换模板</button>{mode==='edit'&&<button aria-pressed={showSource} onClick={()=>setShowSource(v=>!v)}>{showSource?'收起原文':'展开原文'}</button>}</div></div>
    {task&&<div className="revision-task" role="status">{task.progress||'正在处理…'}</div>}{operationError&&<p className="revision-error" role="alert">{operationError}</p>}
    <div className="revision-columns"><main className="revision-manuscript">
      {tool?<><button onClick={()=>setTool(null)}>返回正文</button>{tool==='priority'?<PriorityRevision {...props} onSection={id=>{setSection(id);setMode('edit');setTool(null);}}/>:<FigureWorkspace key={`${project.id}:${artifact.id}`} {...props}/>}</>:mode==='compare'?<><div className="revision-sheet"><small>我的正文 · {section.number}</small><h1>{section.heading}</h1>{version?.paragraphs.map(p=><p className="academic-paragraph" key={p.id}>{p.text}</p>)}{!version?.paragraphs.length&&<p>本节尚无正文，可返回工作台生成完整初稿。</p>}</div>
      <section className="distillation"><header><div><small>模板精读</small><h2>从原文提炼写作方法</h2></div><button className="primary" disabled={disabled||!hasFulltext(paper)||ready} onClick={()=>onRun('template-study',{accessIds:[],text:'完整分析模板的研究设计思路、论证逻辑与语言特点。',templateOptions:{topic:outline.title,articleType:'original'}})}>{ready?'全文分析已保存':study?.status==='reading'?'继续全文分析':'分析完整原文'}</button></header>{!hasFulltext(paper)&&<p>{paper?.document?'请在右侧查阅并确认 PDF 正文完整，再开展全文分析。':'先在右侧取得完整 PDF，再开展全文分析。'}</p>}{study?.status==='reading'&&<p>已分析 {study.coveredPages?.length??0} / {paper.document.pageCount} 页；再次运行将接续已保存结果。</p>}{study&&<><p>{study.coverageNote??study.scope}</p><nav aria-label="原文提炼维度">{Object.entries(dimensions).map(([k,v])=><button key={k} aria-pressed={tab===k} onClick={()=>setTab(k)}>{v}</button>)}</nav>{study.features.filter(f=>f.dimension===tab).map(f=><article key={f.id}><h3>{f.aspect}</h3><p>{f.observation}</p><p><b>用于本研究</b> {f.application}</p><p><b>适用边界</b> {f.boundary}</p>{f.anchors?.map((a,i)=><button className="anchor-link" key={i} onClick={()=>locate(a)}>原文第 {a.page} 页 · {a.quote.slice(0,95)}…</button>)}</article>)}</>}<footer><span>{ready?'全文文字分析已保存，可结合原文开展修订。':'正文可手动修改；模板建议将在全文分析后开放。'}</span><button onClick={()=>setMode('edit')}>进入正文精修<ArrowRight size={16}/></button></footer></section></>:
      <SectionWriter key={`${section.id}:${version?.id}`} compact last={section.id===sections.at(-1).id} {...props} section={section} version={version} saved={saved} onAnchor={locate} onSource={(id,c)=>{setShowFactPdf(false);setFactSource({access:project.accesses[id],source:project.sources[project.accesses[id]?.sourceId],citation:c});setShowSource(true);}} onTemplates={()=>{setMode('compare');setShowSource(true);}} onEdit={async body=>{const result=await onEdit(body);if(result&&body.action==='writing-complete')setSection(sections[sections.findIndex(s=>s.id===section.id)+1]?.id??section.id);return result;}}/>
      }
    </main>{showSource&&tool!=='figures'&&<aside className="revision-reference">{showFactPdf&&<button onClick={()=>{setShowFactPdf(false);setFactSource(null);setPage(1);setAnchor(null);}}>返回模板原文</button>}<div className="revision-fact-source" hidden={!factSource||showFactPdf}>{factSource&&<><header><strong>本句事实依据</strong><button onClick={()=>setFactSource(null)}>返回模板原文</button></header><h2>{factSource.source?.title}</h2><small>{factSource.access?.level==='fulltext'?'全文':'摘要 / 已存片段'} · {factSource.source?.year}</small><blockquote>{factSource.citation?.quote}</blockquote>{factPaper&&<button onClick={()=>{setShowFactPdf(true);setPage(factSource.citation?.anchors?.[0]?.page??1);setAnchor(factSource.citation?.anchors?.[0]??null);}}>核对该来源 PDF</button>}<details><summary>展开已保存原文</summary><p>{factSource.access?.text}</p></details></>}</div>{(!factSource||showFactPdf)&&<PdfReader key={(showFactPdf?factPaper:paper)?.id??'none'} project={project} artifact={artifact} paper={showFactPdf?factPaper:paper} page={page} onPage={setPage} anchor={anchor} onEdit={onTemplateEdit} onRefresh={onRefresh} disabled={disabled}/>}</aside>}</div>
  </dialog>;
}
