import {PdfReader} from './PdfReader.jsx';
import {useEffect,useMemo,useRef,useState} from 'react';
import {sourcePassages} from '../../shared/material-scope.mjs';
import {api,download} from './ui.jsx';
import {literatureRis} from '../../shared/literature-links.mjs';
export function TemplateReader({project,artifact,paper,selection,disabled,onClose,onEdit,onReadZotero,onRefresh}) {
  const dialog=useRef(),[search,setSearch]=useState(''),[active,setActive]=useState(null),[connection,setConnection]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const passages=useMemo(()=>sourcePassages(paper.text??''),[paper.text]),visible=passages.filter(p=>!search.trim()||p.text.toLowerCase().includes(search.toLowerCase())),focus=selection?.focus?.textVersion===paper.textVersion?selection.focus:null;
  useEffect(()=>{dialog.current.showModal();return()=>dialog.current?.close();},[]);
  useEffect(()=>setActive(null),[paper.textVersion]);
  const [pdfPage,setPdfPage]=useState(1);
  const selected=passages.find(p=>p.id===active),readingLevel={abstract:'摘要',title:'题名',fulltext:'全文文字',excerpt:'原文片段'}[paper.level];
  const connect=async()=>{setBusy(true);setError('');try{setConnection(await api.request(`/api/projects/${project.id}/templates/${paper.id}/zotero`));}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <dialog ref={dialog} className="template-reader" onCancel={e=>{e.preventDefault();onClose();}} aria-label="模板原文阅读"><header className="template-reader-head"><div><span>模板原文 · {readingLevel}</span><h2>{paper.title}</h2><small>{paper.authors?.slice(0,3).join(', ')} · {paper.year} · {paper.journal}</small></div><button aria-label="关闭模板原文" onClick={onClose}>关闭</button></header><div className="template-reader-tools"><input type="search" aria-label="在模板原文中查找" placeholder="查找原文关键词…" value={search} onChange={e=>setSearch(e.target.value)}/><span>{visible.length} 个片段</span><a href={paper.url} target="_blank" rel="noreferrer">文献页面 ↗</a><button onClick={()=>download('模板文献.ris',literatureRis([{source:paper,access:{text:paper.text,level:paper.level}}]),'application/x-research-info-systems')}>导出 RIS</button><button disabled={busy} onClick={connect}>{busy?'正在连接…':'连接 Zotero 原文'}</button></div>
  {error&&<p role="alert" className="template-reader-error">{error}</p>}
  <div className="template-reader-layout"><div className="template-original-pdf"><PdfReader project={project} artifact={artifact} paper={paper} page={pdfPage} onPage={setPdfPage} onEdit={onEdit} onRefresh={onRefresh} disabled={disabled}/></div><article hidden={Boolean(paper.document)} className="template-original" aria-label="模板实际读取原文">{paper.level==='abstract'&&<p className="reader-scope">当前保存的是摘要。可通过 Zotero 读取附件文字，或在模板面板补充全文。</p>}{!passages.length&&<p>尚未取得原文。请打开文献页或连接 Zotero。</p>}{passages.length>0&&!visible.length&&<p>未找到匹配文字。可以调整关键词。</p>}{visible.map((p,i)=><section key={p.id} className={`${active===p.id?'reader-selected':''} ${focus?.start===p.start&&focus?.end===p.end?'reader-reference':''}`}><div><small>片段 {passages.indexOf(p)+1}</small><button aria-pressed={active===p.id} onClick={()=>setActive(p.id)}>选作写法参照</button></div><p>{p.text}</p></section>)}</article><aside className="template-reading-notes"><h3>对照阅读</h3><p>分析原文的科学问题与证据组织，选择具有参考价值的论证片段。</p>{selected?<><small>已选片段</small><blockquote>{selected.text}</blockquote><button className="primary" disabled={disabled} onClick={async()=>{if(await onEdit({action:'select-passage',paperId:paper.id,textVersion:paper.textVersion,start:selected.start,end:selected.end})){setActive(null);}}}>用于逐段优化</button></>:focus?<><small>当前写法参照</small><blockquote>{focus.text}</blockquote><button disabled={disabled} onClick={()=>onEdit({action:'select-passage',paperId:paper.id,textVersion:paper.textVersion,clear:true})}>改用整份已读文本</button></>:<p className="reader-scope">尚未指定片段。修改正文时，参考整份已读文本的写作特点。</p>}
  {connection&&<section className="reader-zotero" aria-label="模板 Zotero 附件"><h3>Zotero 原文</h3><p role="status">{connection.message}</p>{connection.matches?.map(m=><a key={m.key} href={m.href}>在 Zotero 查看条目 ↗</a>)}{connection.attachments?.map(a=><div key={a.key}><strong>{a.title}</strong>{a.contentType==='application/pdf'&&<a href={a.href}>在 Zotero 打开 PDF ↗</a>}<button disabled={disabled||busy} onClick={async()=>{setBusy(true);setError('');try{await onReadZotero(paper.id,a.key);}catch(e){setError(e.message);}finally{setBusy(false);}}}>读取这份附件文字</button></div>)}</section>}
  <p className="template-help">读取与选择在本机保存。点击分析或优化时，才使用已配置模型。</p></aside></div><footer><span>{paper.location??'按实际取得的原文范围阅读'}{focus?' · 已选择写法参照片段':''}</span><button onClick={onClose}>返回正文与模板</button></footer></dialog>;
}
