import {continuitySnapshot,selectedRecordText,nestedRef} from '../../shared/research-continuity.mjs';
import {ExportEvidence} from './ExportEvidence.jsx';
import {ParagraphOptimization} from './ResearchTemplates.jsx';
import {useState,useMemo,useEffect} from 'react';
import {ArrowRight,ArrowLeft,FileText,CheckCircle} from '@phosphor-icons/react';
import {writingSections,sectionAccessIds,currentSectionVersion,writingMarkdown,auditLabels} from '../../shared/topic-writing.mjs';
import {screeningSummary} from '../../shared/topic-relevance.mjs';
import {download,date,levels} from './ui.jsx';
import './topic-writing.css';
export function TopicWritingWorkbench({project,artifact,onRun,onEdit,onSource,onOutline,onTemplateEdit,onTemplates,disabled,task}) {
  const w=artifact.topicWorkspace,outline=w.outlines?.find(o=>o.id===(w.activeWritingOutlineId??w.confirmedOutlineId));
  const sections=useMemo(()=>outline?writingSections(outline):[],[outline]);
  const workspace=w.writingWorkspaces?.[outline?.id]??{sections:{},activeSectionId:sections[0]?.id};
  const section=sections.find(s=>s.id===workspace.activeSectionId)??sections[0],saved=workspace.sections[section?.id],version=currentSectionVersion(saved);
  if(!outline)return <section className="writing-empty"><h1>逐段审阅</h1><p>确认研究大纲后，按小节开始写作。</p><button onClick={onOutline}>查看研究大纲</button></section>;
  const reviewed=s=>s?.completedVersionId&&s.completedVersionId===s.activeVersionId;
  const completed=sections.filter(s=>reviewed(workspace.sections[s.id])).length;
  return <section className="writing-workbench" aria-label="分步写作工作台"><header className="writing-page-head"><div><h1>逐段审阅</h1><p>{outline.title}</p></div><button onClick={onOutline}><ArrowLeft size={16}/> 查看大纲</button></header><div className="writing-progress"><strong>{completed} / {sections.length} 节已审阅</strong><progress max={sections.length} value={completed}/><button onClick={()=>download(`${outline.title}-正文草稿.md`,writingMarkdown(outline,workspace),'text/markdown')}>导出正文草稿</button></div>
  <div className="writing-layout"><nav className="writing-sections" aria-label="写作章节">{sections.map(s=><button key={s.id} aria-current={section.id===s.id?'step':undefined} onClick={()=>onEdit({action:'writing-select',outlineId:outline.id,sectionId:s.id})}><span>{s.number}</span><strong>{s.heading}</strong><small>{reviewed(workspace.sections[s.id])?'已审阅':currentSectionVersion(workspace.sections[s.id])?.paragraphs.length?'草稿':'待写作'}</small></button>)}</nav><SectionWriter key={`${outline.id}:${section.id}:${version?.id??'empty'}`} last={section.id===sections.at(-1).id} project={project} artifact={artifact} onTemplateEdit={onTemplateEdit} onTemplates={onTemplates} outline={outline} section={section} version={version} saved={saved} onRun={onRun} onEdit={onEdit} onSource={onSource} disabled={disabled} task={task}/></div></section>;
}
export function SectionWriter({compact=false,onAnchor,last,project,artifact,onTemplateEdit,onTemplates,outline,section,version,saved,onRun,onEdit,onSource,disabled,task}) {
  const key=`rw2:writing-draft:${project.id}:${outline.id}:${section.id}:${version?.id??'empty'}`;
  const [cache]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??{};}catch{return {};}});
  const [language,setLanguage]=useState(cache.language??version?.language??'zh'),[recordText,setRecordText]=useState(cache.recordText??version?.recordText??selectedRecordText(project,continuitySnapshot(project,artifact.id))),[request,setRequest]=useState(cache.request??version?.request??'');
  const [edits,setEdits]=useState(cache.edits??null),[editing,setEditing]=useState(Boolean(cache.edits)),[localError,setLocalError]=useState('');
  const [focusRef,setFocusRef]=useState(null);
  const [outputMode,setOutputMode]=useState(cache.outputMode??version?.mode??(continuitySnapshot(project,artifact.id).protocol?.payload.outputMode==='proposal'?'proposal':/结果|results/i.test(section.chapter)?'results':'literature'));
  const paragraphs=version?.paragraphs??[],dirty=edits!==null&&edits.some((text,i)=>text!==paragraphs[i]?.text),running=task?.mode==='topic-writing'&&task.input.writing?.section.id===section.id;
  const evidence=useMemo(()=>[...new Map(section.evidence.map(e=>[e.ref,e])).values()],[section]);
  useEffect(()=>{try{localStorage.setItem(key,JSON.stringify({language,recordText,request,edits,outputMode}));}catch{setLocalError('浏览器无法保存草稿，请复制正文后再切换。');}},[key,language,recordText,request,edits,outputMode]);
  const run=(auditOnly=false)=>onRun('topic-writing',{accessIds:sectionAccessIds(section),text:request||'按照已确认大纲完成当前小节的学术草稿。',topicOptions:{outlineId:outline.id,sectionId:section.id,language,recordText,outputMode,...(auditOnly?{auditOnly:true}:{})}});
  const save=async()=>{if(await onEdit({action:'writing-save',outlineId:outline.id,sectionId:section.id,baseWritingVersion:version.id,paragraphs:edits})){try{localStorage.removeItem(key);}catch{}setEditing(false);setEdits(null);}};
  const ready=version?.status==='completed',selected=evidence.find(e=>e.ref===focusRef),paper=selected&&outline.papers.find(p=>p.accessId===selected.accessId);
  return <div className={`writing-section-editor ${compact?'writing-compact':''}`}><header><span className="writing-eyebrow">当前小节 · {section.number}</span><h2>{section.heading}</h2><p>{section.purpose}</p></header>
    <details className="writing-brief"><summary>本节论证与文献 · {evidence.length} 篇</summary><p><b>中心命题</b> {section.claim}</p><p>{section.counterpoint}</p><div className="writing-reference-list">{evidence.map(e=><button key={e.ref} onClick={()=>setFocusRef(e.ref)}>[{e.ref.replace(/^R/,'')}] {outline.papers.find(p=>p.accessId===e.accessId)?.title}</button>)}</div>{selected&&<div className="writing-source"><strong>[{selected.ref.replace(/^R/,'')}] {paper?.title}</strong><p>{screeningSummary(paper,paper)}</p><small>{levels[selected.level]}</small><button onClick={()=>onSource(selected.accessId,selected)}>核对已保存原文 ↗</button></div>}</details>
    <details className="writing-settings"><summary>写作要求与方案资料</summary><label>本节成果用途<select aria-label="本节成果用途" value={outputMode} onChange={e=>setOutputMode(e.target.value)} disabled={disabled}><option value="literature">文献论述</option><option value="proposal">拟议方案</option><option value="results">真实结果</option></select></label><label>语言<select aria-label="正文语言" value={language} disabled={disabled} onChange={e=>setLanguage(e.target.value)}><option value="zh">中文</option><option value="en">英文</option></select></label><label>本节要求<textarea aria-label="本节写作要求" value={request} disabled={disabled} onChange={e=>setRequest(e.target.value)} placeholder="例如：强调两组研究条件差异，避免预设阳性结果。" rows={2}/></label><label>本节已确定方案或真实结果<textarea aria-label="本节方案或结果" value={recordText} disabled={disabled} onChange={e=>setRecordText(e.target.value)} placeholder="如有已确定方案或真实结果，在这里提供。尚未实施的研究会按计划表述。" rows={3}/></label></details>
    <div className="writing-workflow" aria-label="本节写作流程"><strong>1 生成正文</strong><span>2 核对依据</span><span>3 逐段优化</span></div><div className="writing-section-actions">{version&&<ExportEvidence projectId={project.id} title={section.heading} refs={[nestedRef('writing',artifact,outline.id,section.id,version.id)]} files={[{name:`${section.heading}.md`,content:version.paragraphs.map(p=>p.text).join('\n\n')}]} disabled={disabled||dirty}/>}{version&&<select aria-label="正文版本" value={version.id} disabled={disabled||dirty} onChange={e=>onEdit({action:'writing-view',outlineId:outline.id,sectionId:section.id,baseWritingVersion:version.id,versionId:e.target.value})}>{saved.versions.map((v,i)=><option key={v.id} value={v.id}>正文 {i+1} · {date(v.at)}{saved.completedVersionId===v.id?' · 已审阅':''}</option>)}</select>}<button className={!ready?'primary':''} disabled={disabled||dirty} onClick={()=>run(false)}>{running?'正在处理当前小节…':!version?'生成本节草稿':!ready?'继续完成本节':'按要求更新草稿'} <ArrowRight size={16}/></button>{paragraphs.length>0&&<button disabled={disabled||dirty} onClick={()=>run(true)}>核对本节依据</button>}{ready&&!editing&&<button onClick={()=>{setEdits(paragraphs.map(p=>p.text));setEditing(true);}}>编辑正文</button>}{editing&&<button onClick={()=>{setEdits(null);setEditing(false);}}>取消编辑</button>}{editing&&<button className="primary" disabled={disabled||!dirty} onClick={save}>保存正文修改</button>}</div>
    {localError&&<p role="alert">{localError}</p>}{dirty&&<p className="writing-local-note">修改已暂存本机，保存后形成新版本。</p>}
    {version?.blueprint&&<details className="paragraph-blueprint"><summary>段落安排 · {version.blueprint.paragraphs.length} 段</summary><p>{version.blueprint.focus}</p><ol>{version.blueprint.paragraphs.map(p=><li key={p.id}><strong>{p.topic}</strong><p>{p.claim}</p><small>{p.relationship} · {p.boundary}</small></li>)}</ol><details><summary>本节材料覆盖</summary>{version.blueprint.coverage.map(c=><p key={c.ref}>[{c.ref.replace(/^R/,'')}] {c.status==='used'?'用于本节':'本节未使用'} · {c.reason}</p>)}</details></details>}
    {!paragraphs.length&&<div className="writing-empty"><FileText size={30}/><h3>本节正文</h3><p>围绕本节命题整合文献。实际研究数据可在初稿形成后补充。</p></div>}
    <div className="writing-paragraphs">{paragraphs.map((p,i)=><article className="writing-paragraph" key={p.id}><div><small>第 {i+1} 段 · {p.topic}</small>{p.audit?.length>0&&<span>{p.audit.some(a=>a.status!=='consistent')?'有待核对事项':'已完成机器核对'}</span>}</div>{editing?<textarea aria-label={`第 ${i+1} 段正文`} value={edits?.[i]??p.text} onChange={e=>setEdits(values=>(values??paragraphs.map(p=>p.text)).map((text,n)=>n===i?e.target.value:text))} rows={Math.max(5,Math.ceil(p.text.length/40))}/>:<p className="academic-paragraph">{p.text}</p>}<div className="writing-paragraph-refs">{[...new Map((p.sentences??[]).flatMap(s=>s.citations).map(c=>[`${c.ref}-${c.passage}`,c])).values()].map(c=><button key={`${c.ref}-${c.passage}`} onClick={()=>onSource(c.accessId,c)}>[{c.ref.replace(/^R/,'')}] {levels[c.level]} · 查看依据</button>)}</div>{!p.audit?.length&&p.sentences?.some(s=>s.checks?.length>0)&&<details className="writing-checks"><summary>本段有待核对事项</summary>{p.sentences.filter(s=>s.checks?.length).map(s=><div key={s.id}><blockquote>{s.text}</blockquote>{s.checks.map((c,i)=><p key={i}>{c.explanation}</p>)}</div>)}</details>}{p.edited&&<small>本段已修改，原机器核对不再适用，待重新审阅。</small>}{p.audit?.length>0&&<details className="writing-audit"><summary>逐句依据核对 · {p.audit.length} 句</summary>{p.audit.map(a=><div key={a.id}><strong>{auditLabels[a.status]}</strong><blockquote>{p.sentences.find(s=>s.id===a.id)?.text}</blockquote><p>{a.explanation}</p>{a.sources?.map((source,i)=><div className="audit-source" key={i}><b>[{source.ref.replace(/^R/,'')}] {auditLabels[source.status]}</b><p>{source.explanation}</p><button onClick={()=>onSource(source.accessId,source)}>查阅本句来源</button></div>)}{a.accessBoundaryApplied&&<small>按实际访问层级保留待核对状态。</small>}</div>)}</details>}{!editing&&<ParagraphOptimization key={p.id} project={project} artifact={artifact} outline={outline} section={section} version={version} paragraph={p} disabled={disabled} onRun={onRun} onEdit={onTemplateEdit} onTemplates={onTemplates} onAnchor={onAnchor}/>}</article>)}</div>
    {version?.blueprint?.needs.length>0&&<details className="writing-needs"><summary>本节待补条件 · {version.blueprint.needs.length} 项</summary><ul>{version.blueprint.needs.map((n,i)=><li key={i}>{n}</li>)}</ul></details>}
    <footer className="writing-next"><small>正文草稿可继续核对与修订，实际研究数据按实施记录补充。</small><button className="primary" disabled={disabled||!ready||dirty} onClick={()=>onEdit({action:'writing-complete',outlineId:outline.id,sectionId:section.id,baseWritingVersion:version.id})}>{saved?.completedVersionId===version?.id?<CheckCircle size={18}/>:null}{last?'完成本节审阅':'审阅本节，继续下一节'} <ArrowRight size={17}/></button></footer>
  </div>;
}
