import {ExportEvidence} from './ExportEvidence.jsx';
import {nestedRef} from '../../shared/research-continuity.mjs';
import { useMemo, useState, useRef } from 'react';
import { ArrowRight, CaretDown, CaretRight, FileText, PencilSimple, Books, Info } from '@phosphor-icons/react';
import { OUTLINE_VERSION, outlineMaterials, outlineMarkdown, outlinePacket, outlineContext, currentOutlineContext } from '../../shared/topic-outline.mjs';
import { topicRelations, screeningSummary } from '../../shared/topic-relevance.mjs';
import { date, download, levels } from './ui.jsx';
import './topic-outline.css';

const roles={direct:'直接依据',indirect:'间接参照',background:'背景桥接'};
const label=ref=>`[${String(ref).replace(/^R/,'')}]`;
function uniqueEvidence(evidence) {
  const papers=new Map();
  for(const e of evidence){const group=papers.get(e.accessId)??{...e,uses:[],anchors:[]};if(e.use&&!group.uses.includes(e.use))group.uses.push(e.use);if(!group.anchors.some(a=>a.passage===e.passage))group.anchors.push(e);papers.set(e.accessId,group);}
  return [...papers.values()].map(e=>({...e,use:e.uses.join('；')}));
}
export function TopicOutlineWorkbench({project,artifact,question,included,ids,onSelection,onAnalyze,onRun,onEdit,onSource,disabled,onWriting}) {
  const w=artifact.topicWorkspace??{},outline=w.outlines?.find(o=>o.id===w.activeOutlineId);
  const [rangeOpen,setRangeOpen]=useState(false),[adjustOpen,setAdjustOpen]=useState(false),[request,setRequest]=useState('');
  const rows=useMemo(()=>outlineMaterials(project,artifact,ids),[project,artifact,ids]);
  const invalid=ids.some(id=>!included.some(r=>r.id===id));
  const same=outline&&JSON.stringify(outlinePacket(rows))===JSON.stringify(outline.papers)&&JSON.stringify(outlineContext(currentOutlineContext(project,artifact,outline.context.request),outline.context.version))===JSON.stringify(outline.context);
  const compile=()=>onRun('topic-outline',{accessIds:ids,text:outline?.context.request??''});
  const generate=()=>onRun('topic-outline',{accessIds:ids,text:request.trim()});
  return <div className="outline-workspace">
    <header className="outline-page-head"><div><h1>研究大纲</h1><p>章节安排与论证依据</p></div><div className="outline-topic"><FileText size={25}/><div><small>当前研究题目</small><strong>{question?.title||question?.text}</strong></div></div></header>
    <section className="outline-scope-band" aria-label="本次大纲材料范围"><FileText size={27}/><strong>本次选择 <b>{ids.length}</b> / {included.length} 篇</strong><button aria-expanded={rangeOpen} onClick={()=>setRangeOpen(!rangeOpen)}>调整范围 <CaretRight size={15}/></button><span>选择小节，查看对应文献与关键发现</span>{!outline&&<button className="primary" disabled={disabled||!ids.length||invalid} onClick={compile}>生成研究大纲 <ArrowRight size={17}/></button>}</section>
    {rangeOpen&&<section className="outline-range"><button disabled={disabled||!included.length} onClick={()=>onSelection(included.map(r=>r.id))}>选择全部已纳入材料</button><div className="use-material-list">{included.map(r=><label key={r.id}><input type="checkbox" disabled={disabled} checked={ids.includes(r.id)} onChange={e=>onSelection(e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}/><span>{r.source.title}</span></label>)}</div></section>}
    {invalid&&<p className="outline-notice">当前选择包含未纳入的材料，请在“调整范围”中重新选择。</p>}
    {outline?<><div className="outline-version-bar"><span>{w.confirmedOutlineId===outline.id?'你已确认这一版':'候选大纲 · 待你确认'}</span><select aria-label="查看大纲版本" value={outline.id} disabled={disabled} onChange={e=>onEdit({action:'view-outline',outlineId:e.target.value})}>{w.outlines.map((o,i)=><option key={o.id} value={o.id}>大纲 {i+1} · {date(o.at)}</option>)}</select><button onClick={()=>download(`${outline.title}-${outline.id}.md`,outlineMarkdown(outline),'text/markdown')}>导出这版大纲</button><ExportEvidence projectId={project.id} title={outline.title} refs={[nestedRef('outline',artifact,null,null,outline.id)]} files={[{name:`${outline.title}.md`,content:outlineMarkdown(outline)}]}/></div>
      {outline.framework!==OUTLINE_VERSION&&<p className="outline-notice">可进一步展开科学问题、论证顺序与证据用途。<button disabled={disabled||invalid} onClick={compile}>深化这版大纲</button></p>}
      {!same&&<p className="outline-notice">材料、发现或研究要求已有变化；当前展示上次保存的大纲。<button disabled={disabled||invalid||!ids.length} onClick={compile}>更新研究大纲</button></p>}
      <OutlineReading key={outline.id} outline={outline} onSource={onSource}/></>:<div className="outline-reading outline-empty"><section><h2>研究大纲</h2><h3>科学问题与章节论证</h3><p>围绕核心问题，安排章节命题、证据对照、竞争解释与待验证条件。</p><p>材料范围与研究决定已保存。大纲与对应文献将在此并列展示。</p></section><aside><h2>证据与依据</h2><p>小节关联的文献会按编号直接列出，附关键发现和本节用途。</p><small>题名、摘要与全文按实际访问层级标注。</small></aside></div>}
    <footer className="outline-actions"><button onClick={()=>setAdjustOpen(!adjustOpen)} aria-expanded={adjustOpen}><PencilSimple size={17}/>调整大纲</button>{outline&&<button disabled={disabled||!ids.length||invalid} onClick={compile}>更新研究大纲</button>}{outline&&<button className="primary" disabled={disabled||(!w.outlineConfirmations?.some(c=>c.outlineId===outline.id)&&!same)} onClick={async()=>{if(w.outlineConfirmations?.some(c=>c.outlineId===outline.id)){if(await onEdit({action:'writing-open',outlineId:outline.id}))onWriting();}else if(await onEdit({action:'confirm-outline',outlineId:outline.id,accessIds:ids}))onWriting();}}>{w.outlineConfirmations?.some(c=>c.outlineId===outline.id)?'继续写作':'确认并开始写作'} <ArrowRight size={17}/></button>}<small>确认后进入写作，按小节生成、审阅与修改正文。</small></footer>
    {adjustOpen&&<form className="outline-adjust" onSubmit={e=>{e.preventDefault();generate();}}><label htmlFor="outline-request">希望怎样调整论证或章节</label><textarea id="outline-request" value={request} onChange={e=>setRequest(e.target.value)} rows={3} placeholder="例如：加强研究之间的条件差异与竞争解释；将主要终点和统计分析分别展开。"/><button className="primary" disabled={disabled||!request.trim()||invalid||!ids.length}>按我的要求生成新版本</button><small>生成新版本后，可继续比较与调整章节。</small></form>}
  </div>;
}
function OutlineReading({outline,onSource}) {
  const initial=outline.sections.length>1?1:0;
  const evidencePanel=useRef(null);
  const [expanded,setExpanded]=useState([initial]),[active,setActive]=useState(outline.sections[initial].children[0].id),[focusedRef,setFocusedRef]=useState(null);
  const chapters=useMemo(()=>outline.sections.flatMap((s,i)=>s.children.map((c,j)=>({...c,number:`${i+1}.${j+1}`}))),[outline]);
  const current=chapters.find(c=>c.id===active)??chapters[0],papers=useMemo(()=>new Map(outline.papers.map(p=>[p.accessId,p])),[outline]);
  const evidence=uniqueEvidence(current.evidence),related=ref=>chapters.filter(c=>c.evidence.some(e=>e.ref===ref));
  const select=(id,ref=null)=>{setActive(id);setFocusedRef(ref);if(ref&&evidencePanel.current?.parentElement.clientWidth<=650)requestAnimationFrame(()=>evidencePanel.current?.scrollIntoView({block:'start',behavior:'instant'}));};
  const showSource=e=>onSource(e.accessId,e);
  return <section className="outline-reading" aria-label="已保存的写作大纲"><div className="outline-tree"><div className="outline-column-title"><h2>研究大纲</h2><span>选择小节，查看对应依据</span></div><details className="outline-positioning"><summary>题目与整篇论证</summary><h3>{outline.title}</h3><p>{outline.route}</p>{outline.positioning&&<dl><dt>核心问题</dt><dd>{outline.positioning.question}</dd><dt>预期贡献</dt><dd>{outline.positioning.contribution}</dd><dt>论述边界</dt><dd>{outline.positioning.scope}</dd></dl>}</details>
      {outline.sections.map((s,i)=><section className="outline-chapter" key={i}><button className="outline-chapter-toggle" aria-expanded={expanded.includes(i)} onClick={()=>setExpanded(expanded.includes(i)?expanded.filter(n=>n!==i):[...expanded,i])}><span className="chapter-number">{i+1}</span><span><strong>{s.heading}</strong><small>{s.purpose}</small></span>{expanded.includes(i)?<CaretDown size={18}/>:<CaretRight size={18}/>}</button>{expanded.includes(i)&&<div className="outline-children">{s.children.map((c,j)=><article className={`outline-child ${c.id===current.id?'selected':''}`} key={c.id}><button className="outline-child-select" aria-pressed={c.id===current.id} onClick={()=>select(c.id)}><b>{i+1}.{j+1}</b><span><strong>{c.heading}</strong><small>{c.purpose}</small></span><CaretRight size={16}/></button><div className="outline-inline-refs"><span>关联文献</span><ReferenceButtons evidence={uniqueEvidence(c.evidence)} onClick={e=>select(c.id,e.ref)}/>{!c.evidence.length&&<small>待补依据</small>}</div>{c.id===current.id&&<details className="outline-argument"><summary>科学问题与论证安排{c.argument?` · ${c.argument.length} 个推进点`:""}</summary>{c.question?<><p className="outline-question">{c.question}</p><p><b>中心命题</b>{c.claim}</p><ol>{c.argument.map((a,k)=><li key={k}>{a.point}<span className="argument-refs">{a.refs.map(ref=><button key={ref} onClick={()=>select(c.id,ref)}>{label(ref)}</button>)}</span></li>)}</ol><p><b>矛盾与边界</b>{c.counterpoint}</p><p><b>章节衔接</b>{c.transition}</p></>:<p>这版只有章节任务，可通过“深化这版大纲”补全论证安排。</p>}{c.figures.length>0&&<p><b>图表计划</b>{c.figures.join('；')}</p>}{c.needs.length>0&&<p className="outline-needs"><b>待补条件</b>{c.needs.join('；')}</p>}</details>}</article>)}</div>}</section>)}
    </div><aside ref={evidencePanel} className="outline-evidence" aria-label="当前小节证据与依据"><div className="outline-column-title"><h2>证据与依据</h2><Info size={17}/></div><div className="outline-evidence-target"><small>当前小节</small><h3>{current.number} {current.heading}</h3><span>{evidence.length} 篇来源文献</span><ReferenceButtons evidence={evidence} onClick={e=>setFocusedRef(e.ref)}/></div><div className="outline-evidence-heading"><strong>相关发现</strong><span>关键发现与本节用途</span></div>{(focusedRef?[...evidence.filter(e=>e.ref===focusedRef),...evidence.filter(e=>e.ref!==focusedRef)]:evidence).map(e=>{const paper=papers.get(e.accessId);return <article className={`outline-evidence-card ${focusedRef===e.ref?'focused':''}`} key={e.accessId}><div><FileText size={23}/><button className="outline-evidence-title" onClick={()=>showSource(e)}>{label(e.ref)} {paper?.title??e.ref}</button></div><p>{paper?screeningSummary(paper,paper):'尚无已存发现，请核对材料。'}</p>{e.use&&<p className="evidence-use"><b>本节用途</b>{e.use}</p>}<div className="outline-source-meta"><span>{roles[e.role]}</span><span>{levels[e.level]??e.level}</span><span>{topicRelations[paper?.relationship]??'待判断'}</span><button onClick={()=>showSource(e)}>查看已保存依据 <ArrowRight size={14}/></button></div>{e.anchors.length>1&&<details className="outline-evidence-links"><summary>已保存依据 · {e.anchors.length} 处片段</summary>{e.anchors.map((anchor,k)=><button key={anchor.passage} onClick={()=>showSource(anchor)}>查看 {label(e.ref)} 的依据片段 {k+1}</button>)}</details>}<details className="outline-evidence-links"><summary>关联章节 · {related(e.ref).map(c=>c.number).join('、')}</summary>{related(e.ref).map(c=><button key={c.id} onClick={()=>{setExpanded([...new Set([...expanded,Number(c.number.split('.')[0])-1])]);select(c.id,e.ref);}}>{c.number} {c.heading}</button>)}</details></article>;})}{!evidence.length&&<p className="outline-no-evidence">本节尚无可用文献依据。{current.needs.join('；')}</p>}<p className="outline-access-note"><Books size={16}/>依据按实际访问层级标注；仅有题名或摘要时，未报告的内容保留为未知。</p></aside></section>;
}
function ReferenceButtons({evidence,onClick}) {
  return <>{evidence.slice(0,5).map(e=><button className="outline-ref" key={e.accessId} aria-label={`查看文献 ${label(e.ref)} 的本节依据`} onClick={()=>onClick(e)}>{label(e.ref)}</button>)}{evidence.length>5&&<details className="outline-extra-refs"><summary>另 {evidence.length-5} 篇</summary>{evidence.slice(5).map(e=><button className="outline-ref" key={e.accessId} onClick={()=>onClick(e)}>{label(e.ref)}</button>)}</details>}</>;
}
